feat(signal): make new package for manage signals
AliMD/vatr pull request #21
Opened 2022-02-26 00:06 UTC by AliMD

2022-02-26 00:08 UTC, AliMD commented
@asmanp2012

2022-02-26 10:11 UTC, asmanp2012 requested changes
Please chnage signals to signalList

2022-02-26 10:11 UTC, asmanp2012 commented on package/signal/src/type.ts
> +  interface VatrSignals
Please change vatarSignals to signalList

2022-02-26 10:11 UTC, asmanp2012 commented on package/signal/src/type.ts
> +  interface VatrRequestSignals
Please change RequestSignals to RequestSignalList

2022-02-27 18:46 UTC, asmanp2012 approved these changes
Everything is ok.

2022-02-27 20:24 UTC, merged