Feat/signal document
AliMD/vatr pull request #40
Opened 2022-03-03 12:04 UTC by MM25Zamanian

2022-03-03 12:18 UTC, AliMD requested changes
موندی چرا اصلا قبلی مرج شد 😠

2022-03-03 12:18 UTC, AliMD commented on package/signal/README.md
> +dispatchSignal('test-event', undefined);
وقتی void تعریف میکنیم یعنی دیگه نباید اینجا پارامتر اصلا بدی

2022-03-03 12:18 UTC, AliMD commented on package/signal/README.md
> +dispatchSignal('test-event', undefined); // this line must make a Error
.

2022-03-03 12:18 UTC, AliMD commented on package/signal/README.md
> +dispatchSignal('test-event', undefined); // this line must make a Error
اصلا expire رو نفهمیدین چیه که !!
چرا باید error بده ؟!!

2022-03-03 12:20 UTC, MM25Zamanian commented on package/signal/README.md
> +dispatchSignal('test-event', undefined); // this line must make a Error
@asmanp2012 من فقط کپی پیست کردم نویسنده جواب بده

2022-03-03 12:20 UTC, MM25Zamanian commented
> موندی چرا اصلا قبلی مرج شد angry

گفتم گند زدم

2022-03-03 20:41 UTC, AliMD requested changes
چرا درستش نمیکنی ؟!

2022-03-05 09:17 UTC, AliMD commented
@MM25Zamanian شما دیگه!

2022-03-05 14:03 UTC, closed without merging