Feat/Utils
AliMD/vatr pull request #50
Opened 2022-03-05 21:41 UTC by MM25Zamanian

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #(issue)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Open an issue for bug report or feature request and mention it to this PR.
- [ ] The commit message follows our guidelines: https://github.com/AliMD/vatr/blob/main/CONTRIBUTING.md#commit-message-format
- [ ] All methods have proper description in `jsdocs` format with `@example` section.
- [ ] Docs have been added / updated (for bug fixes / features).
- [ ] I have performed a self-review of my own code.

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-03-05 22:29 UTC, AliMD requested changes
1. for name and module name must be a same.
2. util is better than utils.
3. we dont need util at this time and need mor discussion.

2022-03-06 22:19 UTC, AliMD commented
این تسک یک دیسکاشن داشت!
چرا پاککک شده!!!

2022-03-06 22:48 UTC, MM25Zamanian commented
> این تسک یک دیسکاشن داشت!
> چرا پاککک شده!!!

من میخواستم کامنتم رو پاک کنم به اشتباه کلا پاکش کردم
یادم نبود چه اجزایی داشت لطفا دوباره بسازید

2022-03-07 13:42 UTC, AliMD commented
خب خودت دوباره با همون فرمون و توضیحات بساز دیگه

2022-03-07 18:10 UTC, MM25Zamanian commented
> خب خودت دوباره با همون فرمون و توضیحات بساز دیگه

متسفانه یادم نیست چی داشت

2022-03-08 13:42 UTC, closed without merging