chore(logger): update contributer list
AliMD/vatr pull request #66
Opened 2022-03-09 15:36 UTC by MM25Zamanian

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #(issue)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Open an issue for bug report or feature request and mention it to this PR.
- [ ] The commit message follows our guidelines: <https://github.com/AliMD/vatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [ ] All methods have proper description in `jsdocs` format with `@example` section.
- [ ] Docs have been added / updated (for bug fixes / features).
- [ ] I have performed a self-review of my own code.

## Other information

2022-03-10 10:59 UTC, AliMD requested changes
۱. لطفا چک های pr رو بخون و اگر انجام شده بزن که عادت کنی
۲. کامیت style..  رو حذف و `push -f` کن
چون هم ربطی به این پول نداره و هم کامیتش اشتباه هستش 
اصلا style چیه ؟!!!

2022-03-10 17:15 UTC, closed without merging

2022-03-11 01:14 UTC, AliMD commented
چرا کلوز کردی ؟!

2022-03-11 07:43 UTC, MM25Zamanian commented
چون کاری که گفتین انجام بده رو بلد نبودم ترسیدم دوباره گند بزنم
گفتم ببندم انجام میدم دوباره باز میکنم یکی دیکه مهم نیست

2022-03-11 09:57 UTC, AliMD commented
میشه خواهش کنم اون گیت مسخره رو زودتر بزنی
خسته شدم دیگه